[build]
  publish = "public"
  command = "npm run build"
  node_bundler = "esbuild"
[build.environment]
  NODE_VERSION = "14.17.0"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"

# All functions
[functions]
  external_node_modules = ["gatsby", "apollo-server-lambda"]

[[plugins]]
  package = "@netlify/plugin-gatsby"

[graph]
  codeGenerator = "netlify-builtin:gatsby"

